name: croppredictor
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
   - streamlit
   - numpy
   - pandas
   - scikit-learn
   - streamlit
   - seaborn
   - matplotlib
   - plotly
